# Generated by Django 4.0.4 on 2022-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
